### ISSUE TITLE
'Delete' fails to delete HITs

### ISSUE THREAD

**Issue by hoonkai** [jtjacques/mturk-manage#1]
Hi

Firstly, great project and good work! I've noticed the 'Delete' button doesn't seem to work. It downloads data instead rather than delete HITs. My guess is 'Delete' is meant to delete all shown HITs. I'm on Chrome.

Cheers

**Comment by jtjacques** [comment]
When attempting to delete multiple HITs, downloading data is mandatory to prevent accidental data loss. As mentioned in the pop-up, this is intentional.

You can only delete HITs which are in a `Reviewable` or `Reviewing` state (i.e. have a grey background) **and** where all submissions have been reviewed (accepted or rejected).

If you attempt to delete HITs which have a white background, or have pending submissions your delete will fail. This check is planned for a future release.

As a work around, please ensure you add `-status/active` to your search terms before attempting bulk deletions. This should hide any HITs which cannot be deleted.

If you wish to delete active HITs you must expire them first, and review all submissions. This is currently a per HIT interaction.

**Comment by hoonkai** [comment]
Got it. Thanks.

**Comment by jtjacques** [comment]
An active HIT warning has been added in release [2018-04-16](https://github.com/jtjacques/mturk-manage/releases/tag/2018-04-16).

Thank you for highlighting this issue.
